[package]
name = "netneighbor"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
chrono = { version = "0.4", features = ["clock"] }
colored = "2.1"
oui-data = "0.2.1"
ctrlc = { version = "3.4", features = ["termination"] }
